# reference: http://www.objc.io/issue-6/travis-ci.html

language: objective-c
osx_image: xcode8
env:
  global:
    - WORKSPACE=Medusa.xcworkspace
    - SDK=iphonesimulator10.1
    - DESTINATION="OS=10.1,name=iPhone 6S"
    - SCHEME=Medusa
script:
  - open -b com.apple.iphonesimulator # Workaround https://github.com/travis-ci/travis-ci/issues/3040
  - xcodebuild -workspace $WORKSPACE -scheme $SCHEME -sdk $SDK -destination "$DESTINATION" -configuration Debug ONLY_ACTIVE_ARCH=NO clean test
notifications:
  email:
    on_success: never

